name: dart_game
description: A game.

environment:
  sdk: '>=2.1.0 <3.0.0'


dependencies:
  postgres: 1.0.2
  yaml: 2.1.15
  dart_game_common:
    path: ../dart_game_common

dev_dependencies:
  test: ^1.0.0
  mockito: ^4.0.0

