analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true
  errors:
    unused_field: error
    missing_return: error
    invalid_assignment: error
    dead_code: error
    missing_required_param: error
    always_declare_return_types: error
    always_put_control_body_on_new_line: error
    always_put_required_named_parameters_first: error
    always_require_non_null_named_parameters: error
    always_specify_types: error
    annotate_overrides: error
    avoid_as: error
    avoid_bool_literals_in_conditional_expressions: error
    avoid_catches_without_on_clauses: error
    avoid_catching_errors: error
    avoid_classes_with_only_static_members: error
    avoid_double_and_int_checks: error
    avoid_empty_else: error
    avoid_field_initializers_in_const_classes: error
    avoid_function_literals_in_foreach_calls: error
    avoid_implementing_value_types: error
    avoid_init_to_null: error
    avoid_js_rounded_ints: error
    avoid_null_checks_in_equality_operators: error
    avoid_positional_boolean_parameters: error
    avoid_private_typedef_functions: error
    avoid_relative_lib_imports: error
    avoid_renaming_method_parameters: error
    avoid_return_types_on_setters: error
    avoid_returning_null: error
    avoid_returning_null_for_void: error
    avoid_returning_this: error
    avoid_setters_without_getters: error
    avoid_single_cascade_in_expression_statements: error
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    avoid_types_on_closure_parameters: error
    avoid_unused_constructor_parameters: error
    avoid_void_async: error
    await_only_futures: error
    camel_case_types: error
    cancel_subscriptions: error
    cascade_invocations: error
    close_sinks: error
    comment_references: error
    constant_identifier_names: error
    control_flow_in_finally: error
    curly_braces_in_flow_control_structures: error
    directives_ordering: error
    empty_catches: error
    empty_constructor_bodies: error
    empty_statements: error
    file_names: error
    flutter_style_todos: error
    hash_and_equals: error
    implementation_imports: error
    invariant_booleans: error
    iterable_contains_unrelated_type: error
    join_return_with_assignment: error
    library_names: error
    library_prefixes: error
    lines_longer_than_80_chars: error
    list_remove_unrelated_type: error
    literal_only_boolean_expressions: error
    no_adjacent_strings_in_list: error
    no_duplicate_case_values: error
    non_constant_identifier_names: error
    null_closures: error
    one_member_abstracts: error
    only_throw_errors: error
    overridden_fields: error
    package_api_docs: error
    package_names: error
    package_prefixed_library_names: error
    parameter_assignments: error
    prefer_adjacent_string_concatenation: error
    prefer_asserts_in_initializer_lists: error
    prefer_collection_literals: error
    prefer_conditional_assignment: error
    prefer_const_constructors: error
    prefer_const_constructors_in_immutables: error
    prefer_const_declarations: error
    prefer_const_literals_to_create_immutables: error
    prefer_constructors_over_static_methods: error
    prefer_contains: error
    prefer_equal_for_default_values: error
    prefer_expression_function_bodies: error
    prefer_final_fields: error
    prefer_final_locals: error
    prefer_foreach: error
    prefer_function_declarations_over_variables: error
    prefer_generic_function_type_aliases: error
    prefer_initializing_formals: error
    prefer_int_literals: error
    prefer_interpolation_to_compose_strings: error
    prefer_is_empty: error
    prefer_is_not_empty: error
    prefer_iterable_whereType: error
    prefer_mixin: error
    prefer_single_quotes: error
    prefer_typing_uninitialized_variables: error
    prefer_void_to_null: error
    public_member_api_docs: error
    recursive_getters: error
    slash_for_doc_comments: error
    sort_constructors_first: error
    sort_pub_dependencies: error
    sort_unnamed_constructors_first: error
    super_goes_last: error
    test_types_in_equals: error
    throw_in_finally: error
    type_annotate_public_apis: error
    type_init_formals: error
    unawaited_futures: error
    unnecessary_brace_in_string_interps: error
    unnecessary_const: error
    unnecessary_getters_setters: error
    unnecessary_lambdas: error
    unnecessary_new: error
    unnecessary_null_aware_assignments: error
    unnecessary_null_in_if_null_operators: error
    unnecessary_overrides: error
    unnecessary_parenthesis: error
    unnecessary_statements: error
    unnecessary_this: error
    unrelated_type_equality_checks: error
    use_rethrow_when_possible: error
    use_setters_to_change_properties: error
    use_string_buffers: error
    use_to_and_as_if_applicable: error
    valid_regexps: error
    void_checks: error
  exclude:
  - test/**


# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
  # from https://github.com/dart-lang/linter/blob/master/example/all.yaml
  - always_declare_return_types
  #- always_put_control_body_on_new_line
  - always_put_required_named_parameters_first
  - always_require_non_null_named_parameters
  #- always_specify_types
  - annotate_overrides
  #- avoid_annotating_with_dynamic
  #- avoid_as
  - avoid_bool_literals_in_conditional_expressions
  # disabled because at least 1 catch is necessary
  # to prevent server crash in case of uncaught exception
  #- avoid_catches_without_on_clauses
  - avoid_catching_errors
  - avoid_classes_with_only_static_members
  - avoid_double_and_int_checks
  - avoid_empty_else
  - avoid_field_initializers_in_const_classes
  - avoid_function_literals_in_foreach_calls
  - avoid_implementing_value_types
  - avoid_init_to_null
  - avoid_js_rounded_ints
  - avoid_null_checks_in_equality_operators
  #- avoid_positional_boolean_parameters
  - avoid_private_typedef_functions
  - avoid_relative_lib_imports
  - avoid_renaming_method_parameters
  #- avoid_return_types_on_setters
  - avoid_returning_null
  - avoid_returning_null_for_void
  - avoid_returning_this
  #- avoid_setters_without_getters
  #- avoid_single_cascade_in_expression_statements
  - avoid_slow_async_io
  - avoid_types_as_parameter_names
  #- avoid_types_on_closure_parameters
  - avoid_unused_constructor_parameters
  - avoid_void_async
  - await_only_futures
  - camel_case_types
  - cancel_subscriptions
  #- cascade_invocations
  - close_sinks
  - comment_references
  - constant_identifier_names
  - control_flow_in_finally
  - curly_braces_in_flow_control_structures
  - directives_ordering
  - empty_catches
  - empty_constructor_bodies
  - empty_statements
  - file_names
  #- flutter_style_todos
  - hash_and_equals
  - implementation_imports
  - invariant_booleans
  - iterable_contains_unrelated_type
  - join_return_with_assignment
  - library_names
  - library_prefixes
  #- lines_longer_than_80_chars
  - list_remove_unrelated_type
  - literal_only_boolean_expressions
  - no_adjacent_strings_in_list
  - no_duplicate_case_values
  - non_constant_identifier_names
  - null_closures
  #- one_member_abstracts
  - only_throw_errors
  - overridden_fields
  - package_api_docs
  - package_names
  - package_prefixed_library_names
  - parameter_assignments
  - prefer_adjacent_string_concatenation
  - prefer_asserts_in_initializer_lists
  - prefer_collection_literals
  - prefer_conditional_assignment
  - prefer_const_constructors
  - prefer_const_constructors_in_immutables
  - prefer_const_declarations
  - prefer_const_literals_to_create_immutables
  #- prefer_constructors_over_static_methods
  - prefer_contains
  - prefer_equal_for_default_values
  #- prefer_expression_function_bodies
  - prefer_final_fields
  - prefer_final_locals
  - prefer_foreach
  - prefer_function_declarations_over_variables
  - prefer_generic_function_type_aliases
  - prefer_initializing_formals
  - prefer_int_literals
  - prefer_interpolation_to_compose_strings
  - prefer_is_empty
  - prefer_is_not_empty
  - prefer_iterable_whereType
  - prefer_mixin
  - prefer_single_quotes
  - prefer_typing_uninitialized_variables
  - prefer_void_to_null
  #- public_member_api_docs
  - recursive_getters
  - slash_for_doc_comments
  #- sort_constructors_first
  - sort_pub_dependencies
  - sort_unnamed_constructors_first
  - super_goes_last
  - test_types_in_equals
  - throw_in_finally
  - type_annotate_public_apis
  - type_init_formals
  #- unawaited_futures
  - unnecessary_brace_in_string_interps
  - unnecessary_const
  - unnecessary_getters_setters
  - unnecessary_lambdas
  - unnecessary_new
  - unnecessary_null_aware_assignments
  - unnecessary_null_in_if_null_operators
  - unnecessary_overrides
  - unnecessary_parenthesis
  - unnecessary_statements
  - unnecessary_this
  - unrelated_type_equality_checks
  - use_rethrow_when_possible
  #- use_setters_to_change_properties
  - use_string_buffers
  - use_to_and_as_if_applicable
  - valid_regexps
  - void_checks

