name: dart_game
description: A game.

environment:
  sdk: '>=2.1.0 <3.0.0'


dependencies:
  postgres: 1.0.2
  yaml: 2.1.15
  json_serializable: ^2.0.0

dev_dependencies:
  test: ^1.0.0
  mockito: ^4.0.0
  build_runner: ^1.0.0
  build_web_compilers: ^1.0.0

