name: dart_game_common
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: johan <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  json_serializable: ^2.0.0

dev_dependencies:
  build_runner: ^1.0.0
  test: ^1.0.0
